// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "bnbr": {
    "ButtonAnimatedBorder": {
      name: "ButtonAnimatedBorder",
      type: "components:ui",
      registryDependencies: undefined,
      files: ["src/registry/bnbr/ui/button-animated-border.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/ui/button-animated-border.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ButtonAnimatedBorderDemo": {
      name: "ButtonAnimatedBorderDemo",
      type: "components:example",
      registryDependencies: [""],
      files: ["src/registry/bnbr/example/button-animated-border-demo.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/example/button-animated-border-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "GridBackgroundDemo": {
      name: "GridBackgroundDemo",
      type: "components:example",
      registryDependencies: [""],
      files: ["src/registry/bnbr/example/grid-background-demo.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/example/grid-background-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "DotBackgroundDemo": {
      name: "DotBackgroundDemo",
      type: "components:example",
      registryDependencies: [""],
      files: ["src/registry/bnbr/example/dot-background-demo.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/example/dot-background-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "WaveBackgroundDemo": {
      name: "WaveBackgroundDemo",
      type: "components:example",
      registryDependencies: [""],
      files: ["src/registry/bnbr/example/wave-background-demo.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/example/wave-background-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
