// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "bnbr": {
    "accordion": {
      name: "accordion",
      type: "components:ui",
      registryDependencies: undefined,
      files: ["src/registry/bnbr/ui/accordion.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/ui/accordion.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button": {
      name: "button",
      type: "components:ui",
      registryDependencies: undefined,
      files: ["src/registry/bnbr/ui/button.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/ui/button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "accordion-demo": {
      name: "accordion-demo",
      type: "components:example",
      registryDependencies: ["accordion"],
      files: ["src/registry/bnbr/example/accordion-demo.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/example/accordion-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-demo": {
      name: "button-demo",
      type: "components:example",
      registryDependencies: ["button"],
      files: ["src/registry/bnbr/example/button-demo.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/example/button-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
