// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "bnbr": {
    "ButtonAnimatedBorder": {
      name: "ButtonAnimatedBorder",
      type: "components:ui",
      registryDependencies: undefined,
      files: ["src/registry/bnbr/ui/ButtonAnimatedBorder.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/ui/ButtonAnimatedBorder.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ButtonAnimatedBorder-demo": {
      name: "ButtonAnimatedBorder-demo",
      type: "components:example",
      registryDependencies: [""],
      files: ["src/registry/bnbr/example/ButtonAnimatedBorder-demo.tsx"],
      component: React.lazy(() => import("@/registry/bnbr/example/ButtonAnimatedBorder-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
